<?xml version="1.0"?>
<robot name="test" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!--Please do not open this robot, this is for testing purposes only. Adding various tags and such to figure out what the different properties actually do-->

<!--Xacro allows to add in variables, as seen below-->
<!--INclude Xacro packages-->
    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobile_base_gazebo.xacro" />
    
<!--Note - you can define more complex components in their own .xacro file to add to the robot file-->
<!--Defining some xacro variables. Defined as xacro:property. Give a name and a value in order to use elsewhere. Changing here will adjust in the whole file.-->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <xacro:property name="pusher_arm_radius" value="0.025" />
    <xacro:property name="pusher_arm_length" value="0.2" />
    <xacro:property name="pusher_length" value="0.1" />
    <xacro:property name="pusher_width" value="0.3" />
    <xacro:property name="pusher_height" value="0.1" />

<!--Materials defied here, no need for exceptional appearance. Color is fine to save resources-->
    <material name="blue">
        <color rgba="0 0 0.5 1" />
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
    </material>


    <link name="base_footprint" /> <!--Self closing link tag, no properties-->
    <!--Link tags here. Links are physical structures in the robot. Joints connect links, can be moveable or immovable-->
    <!--Put all links first and then add joints to keep track-->

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz = "0 0 ${base_height / 2}" rpy="0 0 0" /> <!--Define origin of the shape - set to center of object-->
            <material name="blue" /> <!--Xacro defined the material, line 15. Reusing the name calls back to the predefined variable, allowing you to save time and shorthand-->
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz = "0 0 ${base_height}/2" rpy="0 0 0" />
        </collision>
        <!--Generally, collision and visual will be the same. The exception is the wheel which uses a sphere collision rather than a cylinder, as it behaves oddly otherwise.-->
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
        <!--Add inertia - taken from common_properties.xacro, predefined. You can define this on your own, but using predefined information is best for now until you understand-->
    </link>

    <!--My first item that I add-->
    <link name="drill_cone_link">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/meshes/cone(blender).stl" scale="1 1 1"/>
            </geometry>
            <origin xyz = "0 0 0" rpy="0 ${pi/2} 0" />
            <material name="grey" />
        </visual>

        <collision>
            <geometry>
                <mesh filename="package://my_robot_description/meshes/cone(blender).stl" scale = "1 1 1" />
            </geometry>
            <origin xyz = "0 0 0" rpy="0 ${pi/2} 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${base_length}" o_xyz="0 0 0" o_rpy="0 ${pi/2} 0" />
    </link>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" /> <!--Length is the height of the cylinder-->
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" /> <!--Rotation done in radians, thus in reference to PI-->
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>

        <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="${wheel_radius / 2.0}" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <!--<xacro:include filename="$(find my_robot_description)/urdf/pusharm.urdf.xacro">
    <link name="arm1_link" />-->

        <link name="pusher_arm_link">
        <visual>
            <geometry>
                <cylinder radius="${pusher_arm_radius}" length="${pusher_arm_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${pusher_arm_radius}" length="${pusher_arm_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="3.0" r="${pusher_arm_radius}" l="${pusher_arm_length}" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <link name="pusher_link">
        <visual>
            <geometry>
                <box size="${pusher_length} ${pusher_width} ${pusher_height}" />
            </geometry>
            <origin xyz="0 0 ${pusher_height/2}" rpy="0 0 0" />
            <material name="grey" />
        </visual>

        <collision>
            <geometry>
                <box size="${pusher_length} ${pusher_width} ${pusher_height}" />
            </geometry>
            <origin xyz="0 0 ${pusher_height/2}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="2.0" x="${pusher_length}" y="${pusher_width}" z="${pusher_height}" o_xyz="0 0 ${pusher_height/2}" o_rpy="0 0 0" />
    </link>

    <joint name="pusher_pusher_arm_joint" type="fixed">
        <parent link="pusher_arm_link" />
        <child link="pusher_link" />
        <origin xyz="0 0 ${-pusher_arm_length}" rpy="0 0 0" />
    </joint>

    <joint name="arm_base_link" type="fixed">
        <parent link="base_link" />
        <child link="pusher_arm_link" />
        <origin xyz="${pusher_width/2} ${base_width/2 + pusher_arm_radius*2} ${pusher_arm_length/2 + pusher_height}" rpy="0 0 1.571" />
    </joint>

    <!--Joints here-->
    <!--Joints attach links to each other. DIfferent joint types cause different behaviours. I.E "fixed" disallows movement, would be like welding. COntinuous allows rotation forever. So on.-->
    <!--Origins are where the joint connects the different links - very important to give space for rotation-->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" /> <!--Parent is what child is attached to - any rotation will be done as such-->
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <!--My first joint, attaching drill to chassis-->
    <joint name="base_drill_cone_joint" type="continuous">
        <parent link="base_link" />
        <child link="drill_cone_link" />
        <origin xyz="${base_length} 0 ${wheel_radius}" rpy="0 0 0" />
        <axis xyz="1 0 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} -0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length /4.0} 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 -0.05" rpy="0 0 0" />
    </joint>

    <!--<joint name="base_arm1_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm1_link" />
        <origin xyz="${base_length/2} ${base_width/2 + pusher_arm_radius} 0" rpy="0 0 0" />
    </joint>-->
</robot>